version: "3"
services:
  animal-hero:
    build: .
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=https://animahero.maikemota.com.br/
      - SESSION_SECRET=${SESSION_SECRET}
    restart: unless-stopped
    ports:
      - ${BACKEND_PORT}:3000
    