version: "3"
services:
  backend:
    build: ./backend
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=https://animahero.maikemota.com.br/
      - SESSION_SECRET=${SESSION_SECRET}
    restart: unless-stopped
    ports:
      - 8000:3000
  frontend:
    build: ./frontend
    ports:
      - 8001:3000
    restart: unless-stopped
    